# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.13.1
        uses: actions/setup-node@v1
        with:
          node-version: 12.13.1
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules-v1-${{ hashFiles('package-lock.json') }}
          # loading an older version is fine here, since it will get an npm install
          restore-keys: |
            node_modules-

      - name: Install dependencies
        run: npm install

      - name: Run formatting checks
        run: npm run format-check

      - name: Run linting checks
        run: npm run lint

      - name: Run tests
        run: npm test
